<?php
return array(
     '中国建设银行'=>'CCB_OUT.gif',
     '交通银行'=>'COMM_OUT.gif',
     '中国农业银行'=>'ABC_OUT.gif',
     '中信银行'=>'CITIC_OUT.gif',
     '中国银行'=>'BOC_OUT.gif',
     '广发银行'=>'GDB_OUT.gif',
     '兴业银行'=>'CIB_OUT.gif',
     '中国邮政储蓄银行'=>'PSBC_OUT.gif',
     '中国光大银行'=>'CEB_OUT.gif',
     '平安银行'=>'SPABANK_OUT.gif',
     '杭州银行'=>'HZCB_OUT.gif',
     '中国民生银行'=>'CMBC_OUT.gif',
     '北京农商银行'=>'BJRCB_OUT.gif',    
     '招商银行'=>'to_cmb.jpg',
     '中国工商银行'=>'to_icbc.jpg',
     '上海银行'=>'to_bos.jpg',    
);        